let sampleStockView={rows:[],locations:[],product:null,division:'fabric'}
const sampleStockUnitLabels={piece:'piezas',m:'m',yd:'yd'}
function sampleStockTable(rows,editable=false){return `<div class="sf-table-wrap"><table class="sf-table"><thead><tr><th>Referencia / color</th><th>Ubicación / lote</th><th>Formato</th><th>Existencia</th><th>Reservado</th><th>Disponible</th>${editable?'<th>Conteo</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.products?.name||r.product_id)}</strong><small>${esc(r.color||'Sin color indicado')}</small></td><td>${esc(r.inventory_locations?.name||'')}<small>${esc(r.lot||'Sin lote indicado')}</small></td><td>${esc(r.format)}</td><td data-stock-live="${r.id}" data-stock-field="qty">${Number(r.qty)} ${sampleStockUnitLabels[r.unit]}</td><td data-stock-live="${r.id}" data-stock-field="reserved">${Number(r.reserved)} ${sampleStockUnitLabels[r.unit]}</td><td data-stock-live="${r.id}">${Number(r.qty)-Number(r.reserved)} ${sampleStockUnitLabels[r.unit]}</td>${editable?`<td><details><summary aria-label="Corregir conteo de ${esc(r.products?.name||'muestra')}">${sampleFlowIcon('list')}</summary><label class="sf-label" for="stock-qty-${r.id}">Conteo físico (${sampleStockUnitLabels[r.unit]})</label><input id="stock-qty-${r.id}" type="number" min="${r.reserved}" step="${r.unit==='piece'?1:0.001}" value="${r.qty}"><label class="sf-label" for="stock-reason-${r.id}">Motivo</label><input id="stock-reason-${r.id}" placeholder="Recepción, conteo o corrección"><button class="btn btn-secondary btn-sm" onclick="correctSampleStock('${r.id}',this)">${sampleFlowIcon('save')} Guardar</button></details>${r.unit!=='piece'?`<details><summary>${sampleFlowIcon('box')} Preparar hangers</summary><label class="sf-label" for="stock-used-${r.id}">Longitud consumida (${sampleStockUnitLabels[r.unit]})</label><input id="stock-used-${r.id}" type="number" min="0.001" step="0.001"><label class="sf-label" for="stock-made-${r.id}">Hangers preparados</label><input id="stock-made-${r.id}" type="number" min="1" step="1"><button class="btn btn-secondary btn-sm" onclick="produceSampleHangers('${r.id}',this)">${sampleFlowIcon('save')} Registrar preparación</button></details>`:''}</td>`:''}</tr>`).join('')||`<tr><td colspan="${editable?7:6}">Sin existencia registrada.</td></tr>`}</tbody></table></div>`}
async function showPhysicalSampleStock(div='fabric'){
 sampleStockView.division=div
 const root=showSampleTool('Inventario de '+(div==='fabric'?'telas':'prendas'),'Existencias físicas por color, lote y unidad','samples|'+div+'|inventory');const editable=canDispatchDiv(div)
 const [stock,locations]=await Promise.all([sb.from('sample_stock').select('*,products!inner(name,code,division),inventory_locations(name)').eq('products.division',div).order('updated_at',{ascending:false}).limit(500),sb.from('inventory_locations').select('id,name,key').eq('active',true).order('name')])
 if(stock.error||locations.error){root.innerHTML='<div class="detail-view-inner" role="alert">No se pudo cargar el inventario.</div>';return}
 sampleStockView.rows=stock.data||[];sampleStockView.locations=locations.data||[];sampleStockView.product=null
 root.innerHTML=`<div class="detail-view-inner"><button class="btn btn-secondary" onclick="showSampleCenter('inventory')">${siIcon('arrow-left',16)} Centro de muestras</button><div class="sf-heading"><div><h2>${sampleFlowIcon('box')} Almacenes de Northern Textiles</h2><p>Existencias físicas por color, lote y unidad · ${stock.data.length} registros (hasta 500 recientes)</p></div><button class="btn btn-secondary" onclick="showPhysicalSampleStock('${div}')">${sampleFlowIcon('refresh')} Actualizar</button></div><div class="sf-panel">${editable?`<details><summary>${sampleFlowIcon('box')} Registrar existencia</summary><label class="sf-label" for="stock-product-search">Buscar desarrollo por nombre o código</label><input id="stock-product-search" oninput="searchSampleStockProduct(this.value)" placeholder="Escribe una referencia…"><div id="stock-product-results"></div><div id="stock-entry-form"></div></details>`:''}<label class="sf-label" for="stock-filter">Filtrar los registros cargados</label><input id="stock-filter" placeholder="Referencia, color o lote" oninput="filterSampleStock(this.value)"><div id="stock-table"><p class="sf-hint" data-stock-time>Consulta actual · los saldos se actualizan cada 10 segundos</p>${sampleStockTable(sampleStockView.rows,editable)}</div><p class="sf-error" role="alert" id="stock-error"></p></div></div>`
 watchSampleStock(document.getElementById('stock-table'),()=>sb.from('sample_stock').select('*,products!inner(division)').eq('products.division',div).limit(500))
}
function filterSampleStock(value){const q=value.toLowerCase();document.getElementById('stock-table').innerHTML=sampleStockTable(sampleStockView.rows.filter(r=>[r.products?.name,r.products?.code,r.color,r.lot,r.inventory_locations?.name].join(' ').toLowerCase().includes(q)),canDispatchDiv(sampleStockView.division))}
function searchSampleStockProduct(value){const q=value.trim().toLowerCase();document.getElementById('stock-product-results').innerHTML=q?allProducts.filter(p=>p.division===sampleStockView.division&&[p.name,p.code].join(' ').toLowerCase().includes(q)).slice(0,8).map(p=>`<button class="btn btn-secondary btn-sm" onclick="chooseSampleStockProduct('${p.id}')">${sampleFlowIcon('box')} ${esc(p.name)} · ${esc(p.code||'')}</button>`).join(''):''}
function chooseSampleStockProduct(id){
 const p=allProducts.find(p=>p.id===id);if(!p)return;sampleStockView.product=p
 document.getElementById('stock-product-results').innerHTML='';document.getElementById('stock-product-search').value=p.name
 const formats=p.division==='fabric'?['Hanger','Yard','Meter','Roll Sample']:['Prototype','Mock-up','Fit Sample','Salesman Sample']
 document.getElementById('stock-entry-form').innerHTML=`<fieldset><legend>Formato</legend><div class="sf-options">${formats.map((f,i)=>`<label><input type="radio" name="stock-format" value="${f}" onchange="setSampleStockFormat(this.value)" ${i===0?'checked':''}>${f}</label>`).join('')}</div></fieldset><fieldset><legend>Ubicación</legend><div class="sf-options">${sampleStockView.locations.filter(l=>l.key.startsWith('nt_')).map((l,i)=>`<label><input type="radio" name="stock-location" value="${l.id}" ${i===0?'checked':''}>${esc(l.name)}</label>`).join('')}</div></fieldset><label class="sf-label" for="stock-color">Color</label><input id="stock-color" value="${esc(p.specs?.Color||'')}"><label class="sf-label" for="stock-lot">Lote o identificación del rollo</label><input id="stock-lot"><fieldset><legend>Unidad de esta existencia</legend><div class="sf-options">${[['piece','Piezas'],['m','Metros'],['yd','Yardas']].map(([u,label],i)=>`<label><input type="radio" name="stock-unit" value="${u}" ${i===0?'checked':''}>${label}</label>`).join('')}</div></fieldset><label class="sf-label" for="stock-new-qty">Cantidad física</label><input id="stock-new-qty" type="number" min="0" step="0.001"><label class="sf-label" for="stock-new-reason">Motivo del registro</label><input id="stock-new-reason" value="Conteo inicial"><button class="btn btn-primary" onclick="createSampleStock(this)">${sampleFlowIcon('save')} Registrar existencia</button>`
 setSampleStockFormat(formats[0])
}
async function sampleStockSave(btn,args){btn.disabled=true;try{const {error}=await sb.rpc('adjust_sample_stock',args);if(error)throw error;await showPhysicalSampleStock(sampleStockView.division)}catch(e){document.getElementById('stock-error').textContent=e.message}finally{if(btn.isConnected)btn.disabled=false}}
async function createSampleStock(btn){const p=sampleStockView.product;if(!p)return;await sampleStockSave(btn,{p_product:p.id,p_location:document.querySelector('[name=stock-location]:checked')?.value,p_format:document.querySelector('[name=stock-format]:checked')?.value,p_color:document.getElementById('stock-color').value,p_lot:document.getElementById('stock-lot').value,p_unit:document.querySelector('[name=stock-unit]:checked')?.value,p_qty:document.getElementById('stock-new-qty').value===''?null:Number(document.getElementById('stock-new-qty').value),p_reason:document.getElementById('stock-new-reason').value,p_stock:null,p_expected:null})}
async function correctSampleStock(id,btn){const r=sampleStockView.rows.find(r=>r.id===id);if(!r)return;await sampleStockSave(btn,{p_product:r.product_id,p_location:r.location_id,p_format:r.format,p_color:r.color,p_lot:r.lot,p_unit:r.unit,p_qty:document.getElementById('stock-qty-'+id).value===''?null:Number(document.getElementById('stock-qty-'+id).value),p_reason:document.getElementById('stock-reason-'+id).value,p_stock:r.id,p_expected:r.updated_at})}
async function renderProductPhysicalStock(p){
 const root=document.getElementById('pd-inventory');if(!root)return
 const {data,error}=await sb.from('sample_stock').select('*,products(name),inventory_locations(name)').eq('product_id',p.id)
 if(!root.isConnected)return;root.innerHTML=error?'No se pudo consultar inventario.':sampleStockTable(data||[])
 if(error)return
 const amounts=field=>Object.entries((data||[]).reduce((out,r)=>{out[r.unit]=(out[r.unit]||0)+(field==='available'?Number(r.qty)-Number(r.reserved):Number(r[field]));return out},{})).map(([u,q])=>`${q} ${sampleStockUnitLabels[u]}`).join(' · ')||'Sin registro'
 const set=(id,text)=>{const el=document.getElementById(id);if(el)el.textContent=text}
 set('pd-sa-inv',amounts('available'));set('pd-sa-res',amounts('reserved'));set('pd-sa-status',data?.length?'Inventario registrado':'Sin existencia registrada');set('pd-sa-loc',[...new Set((data||[]).map(r=>r.inventory_locations?.name))].join(' · ')||'—')
 const actions=document.getElementById('pd-inv-actions');if(actions)actions.innerHTML=`<button class="btn btn-secondary btn-sm" onclick="showPhysicalSampleStock('${p.division}')">${sampleFlowIcon('box')} Ver almacén</button>`
}

function setSampleStockFormat(format){
 const unit=format==='Yard'?'yd':format==='Meter'||format==='Roll Sample'?'m':'piece'
 const choice=document.querySelector(`[name="stock-unit"][value="${unit}"]`);if(choice)choice.checked=true
 const key=sampleStockView.division==='garment'?'nt_sample_garments':format==='Hanger'?'nt_sample_hangers':'nt_development_rolls'
 const location=sampleStockView.locations.find(l=>l.key===key);if(location){const radio=document.querySelector(`[name="stock-location"][value="${location.id}"]`);if(radio)radio.checked=true}
}
function watchSampleStock(root,fetchStock){
 const tick=async()=>{
  if(!root.isConnected)return
  if(document.hidden||!root.getClientRects().length){setTimeout(tick,10000);return}
  try{const {data,error}=await fetchStock();if(error)throw error
   const newRows=(data||[]).some(row=>!root.querySelector(`[data-stock-live="${row.id}"]`));
   let notice=root.querySelector('[data-stock-new]');if(newRows&&!notice){notice=document.createElement('p');notice.dataset.stockNew='';notice.className='sf-hint';notice.setAttribute('role','status');root.prepend(notice)}if(notice)notice.textContent=newRows?'Hay lotes nuevos. Usa Actualizar para incorporarlos a la lista.':'';
   for(const row of data||[]){root.querySelectorAll(`[data-stock-live="${row.id}"]`).forEach(cell=>{const field=cell.dataset.stockField||'available';const value=field==='available'?Number(row.qty)-Number(row.reserved):Number(row[field]);cell.textContent=`${value} ${sampleStockUnitLabels[row.unit]}`})}
   const time=root.querySelector('[data-stock-time]');if(time)time.textContent='Actualizado '+new Date().toLocaleTimeString('es')
  }catch(e){const time=root.querySelector('[data-stock-time]');if(time)time.textContent='No se pudo actualizar. Usa Actualizar para reintentar.'}
  if(root.isConnected)setTimeout(tick,10000)
 };setTimeout(tick,10000)
}

async function produceSampleHangers(id,btn){
 const row=sampleStockView.rows.find(r=>r.id===id);if(!row)return
 btn.disabled=true;try{const {error}=await sb.rpc('produce_sample_hangers',{p_source:id,p_expected:row.updated_at,p_length:Number(document.getElementById('stock-used-'+id).value),p_pieces:Number(document.getElementById('stock-made-'+id).value)});if(error)throw error;await showPhysicalSampleStock(sampleStockView.division)}catch(e){document.getElementById('stock-error').textContent=e.message}finally{if(btn.isConnected)btn.disabled=false}
}
