-- ══════════════════════════════════════════════════════════════
-- TALENTO HUMANO — Employee Operations Hub, Phase 1 data model
--
-- Adds the fields and tables the "Colaboradores" module needs to move
-- beyond a static directory + badge queue into real HR workflows
-- (birthdays, anniversaries, organizational movements, tasks) without
-- ever touching payroll/compensation data.
--
-- Idempotent. Run in Supabase > SQL Editor.
-- ══════════════════════════════════════════════════════════════

-- ── 1. EMPLOYEES — fields needed for calculated moments (birthday,
--    anniversary, seniority) and org history (supervisor, category).
--    None of this is payroll data. ──
alter table employees add column if not exists birth_date date;
alter table employees add column if not exists hire_date date;
alter table employees add column if not exists preferred_name text;
alter table employees add column if not exists supervisor_name text;
alter table employees add column if not exists employee_category text; -- e.g. 'staff', 'operator', 'management' — not a pay grade

-- ── 2. EMPLOYEE MOVEMENTS — organizational change history. Never
--    overwrites the employee row silently; each row is an immutable
--    record of a change, effective on a date, with a reason. A
--    future-dated movement stays "scheduled" until applied. ──
create table if not exists employee_movements (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid references employees(id) on delete cascade not null,
  site_id uuid references sites(id) on delete restrict not null,

  movement_type text not null check (movement_type in (
    'new_hire', 'position_change', 'department_change', 'supervisor_change',
    'company_transfer', 'site_transfer', 'status_change',
    'scheduled_departure', 'departure', 'rehire'
  )),

  field text,             -- which employee field this movement changes (e.g. 'position')
  previous_value text,
  new_value text,

  effective_date date not null default current_date,
  reason text,
  note text,

  status text not null default 'scheduled' check (status in ('scheduled', 'applied', 'cancelled')),
  applied_at timestamptz,

  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz default now()
);

create index if not exists employee_movements_employee_idx on employee_movements(employee_id);
create index if not exists employee_movements_effective_idx on employee_movements(site_id, effective_date) where status = 'scheduled';

-- ── 3. TASKS — contextual work items generated by HR workflows
--    (missing photo, prepare birthday card, print badge, review a
--    possible departure from an import, etc). Generic enough to serve
--    every workflow in this module without a table per task type. ──
create table if not exists employee_tasks (
  id uuid primary key default gen_random_uuid(),
  site_id uuid references sites(id) on delete restrict not null,
  employee_id uuid references employees(id) on delete cascade,

  task_type text not null,        -- 'complete_photo', 'complete_birth_date', 'prepare_birthday_card',
                                   -- 'print_badge', 'deliver_badge', 'review_departure', 'resolve_import_conflict', ...
  source text,                    -- what generated it: 'completeness_engine', 'import', 'moments', 'manual'
  source_id uuid,                 -- e.g. the import id, badge issuance id, movement id

  title text not null,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  due_date date,
  assignee uuid references profiles(id) on delete set null,

  status text not null default 'open' check (status in ('open', 'in_progress', 'blocked', 'completed', 'cancelled')),
  blocking_impact text,           -- human-readable: what can't happen until this is resolved

  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz default now(),
  completed_at timestamptz
);

create index if not exists employee_tasks_site_status_idx on employee_tasks(site_id, status);
create index if not exists employee_tasks_employee_idx on employee_tasks(employee_id);

-- ══════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY — same talento_humano role gate as employees,
-- server-side (authorize() is a SECURITY DEFINER function already
-- backing every other table in this module — see update19.sql).
-- ══════════════════════════════════════════════════════════════

alter table employee_movements enable row level security;
alter table employee_tasks enable row level security;

drop policy if exists "talento_humano read movements" on employee_movements;
create policy "talento_humano read movements"
  on employee_movements for select using (authorize('talento_humano', 'read'));

drop policy if exists "talento_humano write movements" on employee_movements;
create policy "talento_humano write movements"
  on employee_movements for insert with check (authorize('talento_humano', 'write'));

drop policy if exists "talento_humano update movements" on employee_movements;
create policy "talento_humano update movements"
  on employee_movements for update using (authorize('talento_humano', 'write'));

drop policy if exists "talento_humano read tasks" on employee_tasks;
create policy "talento_humano read tasks"
  on employee_tasks for select using (authorize('talento_humano', 'read'));

drop policy if exists "talento_humano write tasks" on employee_tasks;
create policy "talento_humano write tasks"
  on employee_tasks for insert with check (authorize('talento_humano', 'write'));

drop policy if exists "talento_humano update tasks" on employee_tasks;
create policy "talento_humano update tasks"
  on employee_tasks for update using (authorize('talento_humano', 'write'));
