import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const sql=async n=>readFile(new URL(`../../../update${n}.sql`,import.meta.url),'utf8');
const user='00000000-0000-4000-8000-000000000001',company='00000000-0000-4000-8000-000000000010';
test('numbering SQL: migration, atomic approval, frozen identity, rollback, retries and access',async()=>{
 const db=new PGlite();
 const call=async(fn,args=[]) => (await db.query(`select ${fn}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as value`,args)).rows[0].value;
 const account=async(role='authenticated')=>db.exec(`reset role;set request.jwt.claim.sub='${user}';set role ${role}`);
 const save=p=>call('policy_cloud_save',[p]),get=id=>call('policy_cloud_get',[id]),approve=p=>call('policy_approve',[p.id,p._revision]);
 const draft=id=>({id,title:'Política de prueba',status:'Borrador',companyId:company,areaCode:'008',code:'FORGED'});
 try{
  await db.exec(`create role anon;create role authenticated;create schema auth;
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   create table profiles(id uuid primary key,email text,full_name text,account_status text,avatar_url text);
   create table capability_grants(user_id uuid,domain text,capability text,resource_id uuid,expires_at timestamptz,granted_by uuid);
   create table index_security_migrations(version integer primary key);
   create function index_account_active() returns boolean language sql stable security definer as $$select exists(select 1 from profiles where id=auth.uid() and account_status='active')$$;
   insert into profiles values('${user}','test','Test Author','active',null);
   insert into capability_grants(user_id,domain,capability) values('${user}','communications','read'),('${user}','communications','write');
   create table countries(id uuid primary key,code text,name text);
   create table companies(id uuid primary key,name text,legal_name text,country_id uuid references countries);
   insert into countries values('${company}','HN','Honduras');
   insert into companies values('${company}','Honduras Spinning Mills','HSM legal','${company}');`);
  const auth=await sql(40);await db.exec(auth.slice(auth.indexOf('create or replace function public.authorize('),auth.indexOf('create or replace function public.get_my_access(')));
  for(const n of [47,48,49])await db.exec(await sql(n));
  await account();await save({...draft('historic'),code:'HN-HSM-008-POL-004'});await save({...draft('old'),code:'POL-2026-001',legacyCode:''});
  await db.exec('reset role');await db.exec(await sql(50));
  const revisions=(await db.query('select count(*)::int as n from policy_revisions')).rows[0].n;
  await db.exec(await sql(50));assert.equal((await db.query('select count(*)::int as n from policy_revisions')).rows[0].n,revisions,'migration is repeatable');
  await account();assert.equal((await get('historic')).code,'HN-HSM-008-POL-004');assert.equal((await get('old')).legacyCode,'POL-2026-001');assert.equal((await get('old')).code,'');
  const catalog=await call('policy_numbering_catalog');assert.equal(catalog.areas.length,13);assert.equal(catalog.companies[0].companyCode,'HSM');
  let a=await save(draft('a'));assert.equal(a.code,'');assert.equal(a.title,'POLÍTICA DE PRUEBA');assert.equal(a.department,'Administración');
  await assert.rejects(save({...a,status:'Aprobada'}),e=>e.code==='22023');
  await assert.rejects(call('policy_save_numbered',[a,true]),e=>e.code==='42501');
  const bad=await save({...draft('invalid'),areaCode:''});await assert.rejects(approve(bad),e=>e.code==='22023');
  const unnamed=await save({...draft('unnamed'),title:'POLÍTICA SIN TÍTULO'});await assert.rejects(approve(unnamed),e=>e.code==='22023');
  const missing=await save({...draft('missing'),companyId:''});await assert.rejects(approve(missing),e=>e.code==='22023');
  a=await approve(a);assert.equal(a.code,'HN-HSM-008-POL-005');assert.equal(a.status,'Aprobada');assert.equal(a.approvedBy,user);
  assert.equal((await call('policy_approve',['a',0]))._revision,a._revision,'lost response retry does not write');
  const edited=await save({...a,title:'Edited',code:'HACK',numbering:{serial:999}});assert.equal(edited.code,a.code);assert.equal(edited.numbering.serial,5);
  await assert.rejects(save({...edited,areaCode:'001'}),e=>e.code==='22023');
  await assert.rejects(save({...edited,companyId:''}),e=>e.code==='22023');
  let b=await save(draft('b')),c=await save(draft('c'));
  const results=await Promise.all([approve(b),approve(c)]);assert.deepEqual(results.map(p=>p.code).sort(),['HN-HSM-008-POL-006','HN-HSM-008-POL-007']);
  const other=await approve(await save({...draft('other'),areaCode:'001'}));assert.equal(other.code,'HN-HSM-001-POL-001');
  b=await save({...results[0],status:'Archivada'});await assert.rejects(approve(b),e=>e.code==='22023');
  b=await save({...b,status:'Borrador'});assert.equal((await approve(b)).code,'HN-HSM-008-POL-006');
  const stale=await save(draft('stale'));await save({...stale,title:'Newer content'});await assert.rejects(approve(stale),e=>e.code==='40001');
  await db.exec('reset role');await db.exec(await sql(51));await db.exec(await sql(51));await account();
  assert.equal((await call('policy_numbering_catalog')).version,51);
  a=await get('a');const approvedTitle=a.title,approvedRevision=a._revision;
  let publications=await call('policy_publication_list',['a']);assert.deepEqual(publications.map(p=>p.versionLabel),['1.0']);assert.equal(publications[0].snapshot.title,approvedTitle);
  await assert.rejects(save({...a,title:'Sobrescritura prohibida'}),e=>e.code==='22023');assert.equal((await get('a')).title,approvedTitle);
  a=await call('policy_set_archived',['a',approvedRevision,true]);assert.equal(a.status,'Archivada');
  await assert.rejects(save({...a,title:'Cambio archivado'}),e=>e.code==='22023');
  a=await call('policy_set_archived',['a',a._revision,false]);assert.equal(a.status,'Aprobada');
  const operation='00000000-0000-4000-8000-000000000051',sourceRevision=a._revision;
  a=await call('policy_create_version',['a',sourceRevision,operation]);assert.equal(a.status,'Borrador');assert.equal(a.version,'2.0');assert.equal(a.code,'HN-HSM-008-POL-005');assert.equal(a.approvedAt,null);
  const retried=await call('policy_create_version',['a',sourceRevision,operation]);assert.equal(retried._revision,a._revision);assert.equal(retried.version,'2.0');
  a=await save({...a,title:'Segunda versión',version:'99.0'});assert.equal(a.version,'2.0','browser cannot forge a version');
  a=await approve(a);assert.equal(a.version,'2.0');assert.equal(a.code,'HN-HSM-008-POL-005');
  publications=await call('policy_publication_list',['a']);assert.deepEqual(publications.map(p=>p.versionLabel),['2.0','1.0']);assert.equal(publications[1].snapshot.title,approvedTitle,'version one remains immutable');
  const simultaneous=await Promise.allSettled([
   call('policy_create_version',['a',a._revision,'00000000-0000-4000-8000-000000000052']),
   call('policy_create_version',['a',a._revision,'00000000-0000-4000-8000-000000000053'])
  ]);assert.equal(simultaneous.filter(result=>result.status==='fulfilled').length,1);assert.equal(simultaneous.filter(result=>result.status==='rejected'&&result.reason.code==='40001').length,1);assert.equal((await get('a')).version,'3.0');
  for(const table of ['policy_code_registry','policy_code_counters','policy_company_codes','policy_publications','policy_version_operations'])await assert.rejects(db.query('select * from '+table),e=>e.code==='42501');
  await db.exec('reset role');await db.exec("update policy_code_counters set last_number=999 where prefix='HN-HSM-008-POL'");await account();
  const exhausted=await save(draft('exhausted'));await assert.rejects(approve(exhausted),e=>e.code==='22023');assert.equal((await get('exhausted')).status,'Borrador');
  await db.exec(`reset role;delete from capability_grants where capability='write'`);await account();await assert.rejects(approve(stale),e=>e.code==='42501');
  await account('anon');await assert.rejects(call('policy_numbering_catalog'),e=>e.code==='42501');await assert.rejects(approve(a),e=>e.code==='42501');await assert.rejects(call('policy_create_version',['a',a._revision,'anon-operation']),e=>e.code==='42501');
 }finally{await db.close()}
});
