import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),core=require('../../policy-review-core.js');
test('anchors disambiguate repetitions and report removed text instead of guessing',()=>{
  const text='Uno igual. Dos igual. Tres final.';
  const a=core.anchor('s:body',text,15,20,'s');
  assert.equal(a.quote,'igual');
  assert.equal(core.locate(a,text).start,15);
  assert.equal(core.locate(a,'Nuevo '+text).start,21);
  assert.equal(core.locate({quote:'igual'},text).status,'orphan');
  assert.equal(core.locate(core.anchor('b','Hola mundo grande',5,17),'Hola ').status,'orphan');
  assert.equal(core.locate(core.anchor('b','Hola mundo grande',5,17),'Hola mundo muy grande').status,'changed');
  const merged=core.merge({a:1,b:1},{a:2,b:1},{a:1,b:2});
  assert.deepEqual(merged,{value:{a:2,b:2},conflicts:[]});
  assert.deepEqual(core.merge({a:1},{a:2},{a:3}).conflicts,['a']);
});
test('real SQL: concurrent comments, author permissions, tombstones, audit, CAS, presence and migration',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create schema auth;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table profiles(id uuid primary key,email text,full_name text,account_status text,avatar_url text);
 create table capability_grants(user_id uuid,domain text,capability text,resource_id uuid,expires_at timestamptz,granted_by uuid);
 create table index_security_migrations(version integer primary key);
 create function index_account_active() returns boolean language sql stable security definer as $$select exists(select 1 from profiles where id=auth.uid() and account_status='active')$$;
 insert into profiles select ('00000000-0000-4000-8000-00000000000'||n)::uuid,'test'||n,'User '||n,'active',null from generate_series(1,3) n;
 insert into capability_grants(user_id,domain,capability) select id,'communications','read' from profiles;
 insert into capability_grants(user_id,domain,capability) select id,'communications','write' from profiles where full_name<>'User 3';`);
 const auth=await readFile(new URL('../../../update40.sql',import.meta.url),'utf8');
 await db.exec(auth.slice(auth.indexOf('create or replace function public.authorize('),auth.indexOf('create or replace function public.get_my_access(')));
 for(const n of [47,48])await db.exec(await readFile(new URL(`../../../update${n}.sql`,import.meta.url),'utf8'));
 const account=async n=>db.exec(`reset role;set request.jwt.claim.sub='00000000-0000-4000-8000-00000000000${n}';set role authenticated;`);
 const call=async(fn,args=[])=> (await db.query(`select ${fn}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as value`,args)).rows[0].value;
 await account(1);await call('policy_cloud_save',[{id:'p',title:'Original',versions:[{id:'old',authorName:'Earlier editor',createdAt:'2026-01-01',snapshot:{title:'Earlier draft'}}],comments:[{id:'legacy',body:'Original legacy',authorName:'Historical',replies:[]}]}]);
 await db.exec('reset role');const migration=await readFile(new URL('../../../update49.sql',import.meta.url),'utf8');await db.exec(migration);await db.exec(migration);
 await account(1);let snapshot=await call('policy_cloud_get',['p']);assert.equal(snapshot._revision,1);assert.equal(snapshot.comments.length,1);
 const apply=op=>call('policy_comment_apply',['p',{operationId:crypto.randomUUID(),threadId:'t',...op}]);
 const op={action:'create',body:'A',anchor:{blockId:'s',quote:'text'},authorId:'FAKE',authorName:'Spoof',operationId:'idempotent'};
 await apply(op);await apply(op);
 await account(2);let result=await apply({action:'reply',messageId:'r',body:'B'});
 const thread=()=>result.threads.find(t=>t.id==='t');
 assert.equal(thread().messages.length,2);assert.equal(thread().authorName,'User 1');assert.equal(thread().messages.find(m=>m.id==='r').authorName,'User 2');
 await assert.rejects(apply({action:'edit',messageId:'t',version:1,body:'Hacked'}),e=>e.code==='42501');
 await assert.rejects(apply({action:'delete-thread',version:1}),e=>e.code==='42501');
 await assert.rejects(apply({action:'delete-thread',threadId:'legacy',version:1}),e=>e.code==='42501');
 await apply({action:'resolve',version:1});
 await assert.rejects(apply({action:'reply',messageId:'late',body:'Late'}),e=>e.code==='40001');
 await account(1);result=await apply({action:'reopen',version:2});
 await apply({action:'edit',messageId:'t',version:1,body:'Edited'});
 await assert.rejects(apply({action:'edit',messageId:'t',version:1,body:'Stale'}),e=>e.code==='40001');
 result=await apply({action:'delete-thread',version:3});assert.equal(thread().deleted,true);
 result=await apply({action:'restore-thread',version:4});assert.equal(thread().deleted,false);
 const history=await call('policy_comment_history',['p','t']);assert.ok(history.some(e=>e.action==='edit'&&e.before.body==='A'));
 const saved=await call('policy_cloud_save',[{...snapshot,title:'Changed',comments:[]}]);assert.equal(saved.comments.length,2);
 const versions=await call('policy_revision_list',['p']);assert.ok(versions.some(v=>v.snapshot.title==='Earlier draft'&&v.legacy));assert.ok(versions.some(v=>v.snapshot.title==='Changed'&&v.authorName==='User 1'));
 await assert.rejects(call('policy_cloud_delete',['p']),e=>e.code==='42501');
 const localMigrated=await call('policy_cloud_save',[{id:'local-only',title:'Migrated',comments:[{id:'local-comment',body:'Still here',authorName:'Legacy author',createdAt:'2025-01-01'}]}]);assert.equal(localMigrated.comments[0].messages[0].body,'Still here');assert.match(localMigrated.comments[0].createdAt,/2025/);
 await assert.rejects(call('policy_cloud_save',[snapshot]),e=>e.code==='40001');
 await assert.rejects(call('policy_cloud_save',[{id:'p',title:'Old client'}]),e=>e.code==='40001');
 await call('policy_presence_touch',['p']);await account(2);assert.equal((await call('policy_presence_touch',['p'])).length,2);
 await account(3);await assert.rejects(apply({action:'reply',messageId:'view',body:'No'}),e=>e.code==='42501');
 await assert.rejects(db.query('select * from policy_comment_events'),e=>e.code==='42501');
 await db.exec('reset role;set role anon');await assert.rejects(call('policy_comments_read',['p']),e=>e.code==='42501');
 }finally{await db.close()}
});
