const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const source=fs.readFileSync(require('node:path').join(__dirname,'../../index.html'),'utf8');
const dom=new JSDOM('<div id="pg"></div><div id="sec-title"></div><div id="sec-sub"></div>',{url:'https://test.local',runScripts:'outside-only'});
const w=dom.window;w.eval=code=>vm.runInContext(code,dom.getInternalVMContext());w.esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');w.escAttr=w.esc;w.siIcon=()=>'';w.setSecCrumbs=()=>{};w.requestAnimationFrame=()=>{};w.document.queryCommandState=()=>false;
w.jsStr=v=>String(v??'').replaceAll("'","\\'");w.clearSecCrumbs=()=>{};w.toast=()=>{};
w.eval(source.slice(source.indexOf('function pdSelect('),source.indexOf('/* ═',source.indexOf('function pickPdSelect('))));
let scripts=0;for(const match of source.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(!match[2].trim()||/application\/ld\+json/.test(match[1]))continue;new vm.Script(match[2]);scripts++}console.log(`PASS: syntax of ${scripts} inline scripts`);
const start=source.indexOf("const COMMS_STORE_KEY="),end=source.indexOf('\n',source.indexOf('function printCommunicationMemo()',start));
w.eval('const LBL_LOGO_SVG="";\n'+source.slice(start,end));

w.eval(source.slice(source.indexOf('const SI_ICON = {'),source.indexOf('// StatusBadge (',source.indexOf('const SI_ICON = {'))));

w.HTMLElement.prototype.scrollIntoView=function(){};
let checks=0;function test(name,fn){fn();console.log('PASS: '+name);checks++}
w.eval("_commsCurrent=commsNormalize(createCommunicationDraft({blocks:[{id:'flow-test',type:'process',color:'#16cdbe',steps:[{title:'Recibir solicitud',description:'Datos iniciales'},{title:'Validar',description:'Revisar datos'},{title:'Entregar',description:'Confirmar recepción'}]}]}))");
w.renderCommunicationEditor();
let block=()=>w.commsFlowBlock('flow-test');
test('legacy stages keep content, numbering and individual inherited color',()=>{const steps=block().steps;assert.equal(steps.length,3);assert.equal(steps[0].title,'Recibir solicitud');assert.equal(steps[0].color,'#16cdbe');assert.equal(w.commsFlowMarker(steps[0],0),'01');const ids=steps.map(s=>s.uid);w.commsFlowNormalize(block());assert.deepEqual(Array.from(block().steps,s=>s.uid),Array.from(ids))});
test('individual shape, icon and color persist without changing sibling stages',()=>{const uid=block().steps[0].uid;w.commsFlowSet('flow-test',uid,'shape','diamond',true);w.commsFlowSet('flow-test',uid,'marker','icon',true);w.commsFlowSet('flow-test',uid,'icon','mail',true);w.commsFlowSet('flow-test',uid,'color','#c5e9ff',true);w.commsPersist();w.openCommunicationDraft(w.eval('_commsCurrent.id'));assert.equal(block().steps[0].icon,'mail');assert.equal(block().steps[0].shape,'diamond');assert.equal(block().steps[1].color,'#16cdbe')});
test('layout selector updates the current record after autosave replaces its object',()=>{w.renderCommunicationEditor();const button=w.document.querySelector('[aria-label="Distribución del flujograma"]'),id=button.parentElement.querySelector('input').id;w.commsPersist();w.commsSelectChanged('vertical',id);assert.equal(block().layout,'vertical');w.commsPersist();w.openCommunicationDraft(w.eval('_commsCurrent.id'));assert.equal(block().layout,'vertical')});
test('icon catalog exists and the exported SVG is valid with escaped user text',()=>{for(const [key]of w.eval('COMMS_FLOW_ICONS'))assert.ok(w.siIcon(key));block().steps[0].title='<script>bad</script>';const html=w.memoFlowHtml(block()),node=new w.DOMParser().parseFromString(html,'text/html').querySelector('svg');const parsed=new w.DOMParser().parseFromString(new w.XMLSerializer().serializeToString(node),'image/svg+xml');assert.equal(parsed.querySelector('parsererror')?.textContent,undefined);assert.equal(node.querySelector('script'),null);assert.ok(node.querySelector('svg[stroke]'));assert.ok(node.textContent.includes('<script>bad</script>'));assert.ok(w.memoImageDocumentHtml(w.eval('_commsCurrent')).includes('Flujograma:'))});
test('duplicate and reorder preserve stage identity and auto numbering follows order',()=>{w.commsFlowAction('flow-test','duplicate');assert.equal(block().steps.length,4);assert.notEqual(block().steps[0].uid,block().steps[1].uid);const copy=block().steps[1];copy.description='Solo copia';assert.notEqual(block().steps[0].description,copy.description);w.commsFlowAction('flow-test','down');assert.equal(block().steps[2].uid,copy.uid);assert.equal(w.commsFlowMarker({marker:'number',numberStyle:'roman'},3),'IV');assert.equal(w.commsFlowMarker({marker:'number',numberStyle:'letters'},26),'AA');assert.equal(w.commsFlowMarker({marker:'number',numberStyle:'custom',number:'A2'},3),'A2')});
test('long content stays complete and layouts connect every stage',()=>{const b=block();b.steps[0].description='detalle '.repeat(60);const expected=w.commsFlowWrap(b.steps[0].description,15).join(' ').trim();for(const layout of ['horizontal','vertical']){b.layout=layout;const doc=new JSDOM(w.memoFlowHtml(b)).window.document;assert.equal(doc.querySelectorAll('polyline').length,b.steps.length-1);assert.equal((doc.querySelector('svg').textContent.match(/detalle/g)||[]).length,60);assert.ok(!doc.querySelector('svg').outerHTML.includes('NaN'))}assert.ok(expected.length>0)});
test('last stage can be removed and restored with undo',()=>{while(block().steps.length)w.commsFlowAction('flow-test','delete');assert.equal(w.memoFlowHtml(block()),'');w.commsUndoEdit();assert.equal(block().steps.length,1)});
test('flow text contrasts correctly with light and dark brand colors',()=>{assert.equal(w.commsFlowInk('#16cdbe'),'#0b0b0b');assert.equal(w.commsFlowInk('#004a86'),'#ffffff');assert.equal(w.commsFlowInk('#ffffff'),'#0b0b0b')});
console.log(checks+' flowchart checks passed');w.close();
