const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict')
const {JSDOM}=require('jsdom')
const dom=new JSDOM('<!doctype html><div id="tb-section"></div><div id="product-controls"></div><div id="sec-title"></div><div id="sec-sub"></div><div id="pg"></div>',{url:'https://test.local',runScripts:'outside-only'})
const w=dom.window
Object.assign(w,{
  me:{id:'new-hire-test'},_navLeaf:null,
  syncModule(){},leaveView(){},renderSidebarTree(){},clearSecCrumbs(){},toast(){},confirm:()=>true,
  requestAnimationFrame:fn=>fn(),
  esc:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),
  escAttr:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),
  siIcon:name=>`<svg data-icon="${name}"></svg>`,memoLogoHtml:()=>'<div class="memo-logo">SIERRA</div>'
})
w.eval=code=>vm.runInContext(code,dom.getInternalVMContext())
w.eval(fs.readFileSync(path.join(__dirname,'../../js/new-hire-builder.js'),'utf8'))

w.showNewHireCreator()
assert.equal(w.document.getElementById('sec-title').textContent,'Altas de colaborador')
assert.equal(w.document.querySelector('.new-hire-art').offsetWidth,0)
assert.match(w.document.querySelector('.new-hire-art').getAttribute('style'),/--nh-primary:#62b8b1/)
assert.equal(w.document.querySelectorAll('.new-hire-tab').length,2)
w.newHireOpenTab('design')
assert.equal(w.document.querySelectorAll('.new-hire-palette').length,4)
assert.equal(w.document.querySelectorAll('select').length,0)
assert.match(w.document.querySelector('.new-hire-clay').src,/sierra-clay-welcome-team\.png$/)
assert.ok(w.document.querySelector('.new-hire-card-grid'))
assert.ok(w.document.querySelector('.new-hire-info'))
assert.ok(w.document.querySelector('.new-hire-message-card'))
assert.equal(w.document.querySelectorAll('.new-hire-heading-note').length,0)
assert.equal(w.document.querySelectorAll('.new-hire-art-title > span').length,2)
assert.equal(w.document.querySelector('.new-hire-art-title > span:last-child').textContent,'al equipo SIERRA')
assert.match(w.document.querySelector('.new-hire-message').textContent,/Nos alegra que formes parte/)
assert.equal(w.document.querySelectorAll('[data-nh-field="phone"]').length,0)
assert.equal(w.document.querySelector('.new-hire-name').textContent,'Nombre del colaborador')
w.newHireOpenTab('content')
assert.ok(w.document.getElementById('new-hire-field-phone'))
assert.ok(w.document.getElementById('new-hire-field-startDate'))
assert.equal(w.document.querySelectorAll('.new-hire-grid').length,0)
w.newHireSet('name','Ana Martínez')
w.newHireSet('role','Analista de Desarrollo')
w.newHireSet('department','Talento Humano')
w.newHireSet('phone','+504 9999-9999')
assert.equal(w.document.querySelector('.new-hire-name').textContent,'Ana Martínez')
assert.ok(w.document.querySelector('.new-hire-name').classList.contains('new-hire-single-line'))
assert.equal(w.document.querySelector('.new-hire-role').textContent,'Analista de Desarrollo')
assert.equal(w.document.querySelector('.new-hire-department').textContent,'Talento Humano')
assert.equal(w.document.querySelector('[data-nh-field="phone"]').textContent,'+504 9999-9999')
assert.equal(w.document.querySelector('[data-nh-field="email"] svg').dataset.icon,'mail')
assert.ok(w.document.querySelector('[data-nh-field="email"] .new-hire-contact-value').classList.contains('new-hire-single-line'))
assert.equal(w.document.querySelector('[data-nh-field="phone"] svg').dataset.icon,'phone')
assert.ok(w.document.querySelector('.new-hire-fact-department'))
assert.ok(w.document.querySelector('.new-hire-fact-date'))
w.newHireFocusField('name')
assert.equal(w.document.activeElement.id,'new-hire-field-name')
w.newHirePalette('orange')
assert.match(w.document.querySelector('.new-hire-art').getAttribute('style'),/--nh-primary:#dd6e28/)
assert.match(w.document.querySelector('.new-hire-art').getAttribute('style'),/--nh-accent:#dd6e28/)
assert.equal(JSON.parse(w.localStorage.getItem('index_new_hire_v1:new-hire-test')).palette,'orange')
w.newHireReset()
assert.equal(w.document.querySelector('.new-hire-name').textContent,'Nombre del colaborador')
console.log('PASS: new-hire creator renders, updates, stores and resets the SIERRA welcome art')
