const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '../..')
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8')
const migration = fs.readFileSync(path.join(root, 'update47.sql'), 'utf8')
const presenceMigration = fs.readFileSync(path.join(root, 'update48.sql'), 'utf8')

assert.match(migration, /create table if not exists public\.policy_documents/)
assert.match(migration, /snapshot jsonb not null/)
assert.match(migration, /function public\.policy_cloud_list\(\)/)
assert.match(migration, /function public\.policy_cloud_save\(p_snapshot jsonb\)/)
assert.match(migration, /authorize\('communications','read'\)/)
assert.match(migration, /authorize\('communications','write'\)/)
assert.match(migration, /revoke all on public\.policy_documents from public,anon,authenticated/)
assert.match(migration, /index_security_migrations\(version\) values\(47\)/)
assert.match(presenceMigration, /create table if not exists public\.policy_presence/)
assert.match(presenceMigration, /function public\.policy_presence_touch\(p_policy_id text\)/)
assert.match(presenceMigration, /revoke all on public\.policy_presence from public,anon,authenticated/)
assert.match(presenceMigration, /account\.full_name/)
assert.match(presenceMigration, /index_security_migrations\(version\) values\(48\)/)

assert.match(html, /const POLICY_CLOUD_MIGRATION_KEY='sierra_policies_cloud_migrated_v1'/)
assert.match(html, /async function policyLoad\(\)/)
assert.match(html, /sb\.rpc\('policy_cloud_list'\)/)
assert.match(html, /sb\.rpc\('policy_cloud_save',\{p_snapshot:snapshot\}\)/)
assert.match(html, /missing\.map\(policyCloudSave\)/)
assert.match(html, /function policyQueueCloudSave\(policy\)/)
assert.match(html, /policyQueueCloudSave\(copy\)/)
assert.match(html, /policyQueueCloudSave\(policy\)/)
assert.match(html, /policyQueueCloudSave\(p\)/)
assert.match(html, /Guardado en la nube/)
assert.match(html, /Sin conexión · copia local conservada/)
assert.match(html, /Cargando políticas de la nube…/)

console.log('PASS: policies use authenticated cloud persistence with one-time local migration')
